### ISSUE TITLE
Hub v2 related issues?

### ISSUE THREAD

**Issue by alexruffell** [rayzurbock/SmartThings-BigTalker#11]
Hi Rayzurbock, 

I have recently migrated to hub v2 and I am now trying to fix a number of issues that may or may not be related to hub v2.

While trying to figure out why BigTalker is no longer calling out my door contacts read through AlarmServer (Raspberry Pi translation between DSC alarm and ST) I found lots of error messages from BigTalker in the logs. Any idea what they are?

5:34:47 PM: error groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method physicalgraph.app.api.CoreApi#toDateTime.
Cannot resolve which method to invoke for [null, class sun.util.calendar.ZoneInfo] due to overlapping prototypes between:
[class java.lang.String, class java.lang.Object]
[class java.util.Date, class java.lang.Object] @ line 2879

5:34:27 PM: error groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method physicalgraph.app.api.CoreApi#toDateTime.
Cannot resolve which method to invoke for [null, class sun.util.calendar.ZoneInfo] due to overlapping prototypes between:
[class java.lang.String, class java.lang.Object]
[class java.util.Date, class java.lang.Object] @ line 2879

5:32:33 PM: error groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method physicalgraph.app.api.CoreApi#toDateTime.
Cannot resolve which method to invoke for [null, class sun.util.calendar.ZoneInfo] due to overlapping prototypes between:
[class java.lang.String, class java.lang.Object]
[class java.util.Date, class java.lang.Object] @ line 2879

Regards,
Alex

**Comment by rayzurbock** [comment]
Thanks.  I believe I have found the error.  When setting a motion 1 start time and motion 1 end time announcement restriction, the code erroneously uses motion 2 end time, which is likely null in your case.

case "motion":
    if (index == 1 && (!(settings.motionStartTime1 == null))) {
This is where it is giving an error >>>>        if (timeOfDayIsBetween(settings.motionStartTime1, settings.motionEndTime2, now, location.timeZone)) { return true } else { return false }
    }

Correcting and posting to RELEASE 1.1

**Comment by rayzurbock** [comment]
Should be corrected now.  Do you mind loading the new code and letting me know if your custom time restrictions on Motion 1 work properly now?  (You will need to load the new code, then go back into the settings for Motion 1, set your time restrictions and hit done until all is saved).

**Comment by alexruffell** [comment]
Hi @rayzurbock , it is working now. Thanks!

**Comment by rayzurbock** [comment]
Excellent.  Thanks for the update.
