### ISSUE TITLE
Open Contact Issue

### ISSUE THREAD

**Issue by ski36** [rayzurbock/SmartThings-BigTalker#14]
Your app seems to do what I want to be able to do with my Sonos speakers, but I have tried the 1.1.3 and the 1.1.4 beta 7 versions. Both have the same issue ... works when door is closed, but it fails when attempting to broadcast when door is opened.

Errors . . .

BigTalker couldn't announce:

ST Platform issue?
textToSpeech() failed.

Any suggestions would be great. Thanks

**Comment by rayzurbock** [comment]
SmartThings has experienced an issue with their text to speech (TTS) service for a while now which would prevent it from converting text to spoken audio.  1.1.4.Beta versions added a detection for this failure and produces the error message that you have shown here.  

Approximately 3 days ago, SmartThings resolved the issues with their TTS service.
I also just released BigTalker 1.1.4-Beta8 resolving a number of issues.
Can you please test again and see if this is resolved for you?

**Comment by ski36** [comment]
It’s working now.

 

Thanks !!

**Comment by rayzurbock** [comment]
Thanks for responding.  I'll go ahead and close this issue as resolved then.  Thank you.
