### ISSUE TITLE
%lastmode% not retaining correct value of Last Mode 

### ISSUE THREAD

**Issue by tuhinz** [rayzurbock/SmartThings-BigTalker#14]
P2.0.a8 / C2.0.a7:

Set up Bigtalker to announce change of mode as follows:
Say this when home mode is changed: %locationname% mode has changed from %lastmode% to %mode%.

Whenever it speaks it picks up "lastmode" as "free roam" which was one of the modes i once had set up but have since  deleted. Looking at the log (see below), the Last Mode is correctly identified under onModeEvent but the output statement picks up "free roam" instead of whatever the Last Mode actually is.

FYI,  before I installed the .0 beta version, the same line used to work fine.

22:57:48: trace BIGTALKER-DEV-PARENT(P2.0.a8) || [PARENT] TALK(Common_mode-presense_change.mode) |sS| AudioHook | Sending speak().
22:57:48: trace BIGTALKER-DEV-PARENT(P2.0.a8) || [PARENT] TALK(Common_mode-presense_change.mode) |sS| >> hello toohheen - home mode has changed from free roam to Roaming.
22:57:48: debug BIGTALKER-DEV-PARENT(P2.0.a8) || [PARENT] TALK(myDelay=100)
22:57:48: debug BIGTALKER-DEV-PARENT(P2.0.a8) || [CHILD:Common_mode-presense_change] (onModeEvent): Last Mode: Home, New Mode: Roaming
22:57:20: trace BIGTALKER-DEV-PARENT(P2.0.a8) || [PARENT] TALK(Common_mode-presense_change.mode) |sS| AudioHook | Sending speak().
22:57:20: trace BIGTALKER-DEV-PARENT(P2.0.a8) || [PARENT] TALK(Common_mode-presense_change.mode) |sS| >> hello toohheen - home mode has changed from free roam to Home.
22:57:20: debug BIGTALKER-DEV-PARENT(P2.0.a8) || [PARENT] TALK(myDelay=100)
22:57:20: debug BIGTALKER-DEV-PARENT(P2.0.a8) || [CHILD:Common_mode-presense_change] (onModeEvent): Last Mode: Roaming, New Mode: Home

**Comment by rayzurbock** [comment]
Thanks for the detailed report which I have used to locate the issue.  I will come up with a plan to resolve it.
The issue was introduced when the SmartApp was split into the Parent/Child structure to support unlimited event groups.

**Comment by rayzurbock** [comment]
Resolved in Parent App version "P2.0.a9"
