### ISSUE TITLE
Add delay at beginning of phrase

### ISSUE THREAD

**Issue by bucks7756** [rayzurbock/SmartThings-BigTalker#20]
Question, when big talker is run, it sometimes cuts off the first couple of words.  Is there a way to add in a delay at the beginning of a phrase to allow some time to process it?  For example (say nothing for 2 seconds, then "The dryer is finished").

**Comment by rayzurbock** [comment]
I do not experience this issue.
SmartThings does not introduce a short delay ability (such as a sleep() function) into their API other than scheduling actions for a later time. You can schedule actions to occur at a later time, but they highly discourage and do not support using a schedule of less than 60 seconds.

Are you perhaps sending audio to a bluetooth (or other wireless) audio receiver?
What are you sending the audio to?

**Comment by bucks7756** [comment]
Ok.  Thanks for the info.  Yes, it's going to a Bluetooth speaker controlled via a raspberry pi.

Sent from Yahoo Mail on Android 
 
  On Tue, Mar 15, 2016 at 1:57 PM, Brian Lowrance<notifications@github.com> wrote:   
I do not experience this issue.
SmartThings does not introduce a short delay ability (such as a sleep() function) into their API other than scheduling actions for a later time. You can schedule actions to occur at a later time, but they highly discourage and do not support using a schedule of less than 60 seconds.

Are you perhaps sending audio to a bluetooth (or other wireless) audio receiver?
What are you sending the audio to?

**Comment by rayzurbock** [comment]
I would suggest searching for solutions regarding your O.S., Bluetooth, and VLC delay.
This sounds like an issue where audio is being sent to play by VLC, before the bluetooth device is ready to play.
Possible search phrases (you may want to add your O.S. to the phrase; ie: windows, linux, mac):
vlc bluetooth audio sync
vlc bluetooth delay start

**Comment by bucks7756** [comment]
Thanks for the help.  I found the bluetooth was going into sleep mode and was able to disable that.  Working well now.  One issue I just found is that my contact group 3 is not working.  1 and 2 work fine but three doesn't send a command to vlc.  I moved my contact from 3 to 2 to make sure it wasn't the contact and it worked fine.  Do you know if there is an issue with contact group 3?  Thanks.
--------------------------------------------
On Tue, 3/15/16, Brian Lowrance <notifications@github.com> wrote:

 Subject: Re: [SmartThings-BigTalker] Add delay at beginning of phrase (#20)
 To: "rayzurbock/SmartThings-BigTalker" <SmartThings-BigTalker@noreply.github.com>
 Cc: "bucks7756" <bucks7756@yahoo.com>
 Date: Tuesday, March 15, 2016, 9:04 PM
 
 I would suggest searching for
 solutions regarding your O.S., Bluetooth, and VLC delay.
 
 This sounds like an issue where audio is being sent to play
 by VLC, before the bluetooth device is ready to play.
 
 Possible search phrases (you may want to add your O.S. to
 the phrase; ie: windows, linux, mac):
 
 vlc bluetooth audio sync
 
 vlc bluetooth delay start
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly or view
 it on GitHub

**Comment by rayzurbock** [comment]
Would you mind submitting this as a new issue on GitHub "One issue I just found is that my contact group 3 is not working.".  I've verified that this does exist and is the result of a typo.  I'd like to add it to my list for the next release.
