### ISSUE TITLE
Icons no longer working

### ISSUE THREAD

**Issue by dancwilliams** [rayzurbock/SmartThings-BigTalker#3]
Hello,

It looks like the location for the icons is no longer valid:

**Not Found**

The requested URL /ST/icons/BigTalker-118.png was not found on this server.`

Same response for all icons:

`iconUrl: "http://rayzurbock.com/ST/icons/BigTalker-118.png",
  iconX2Url: "http://rayzurbock.com/ST/icons/BigTalker@2x-118.png",
  iconX3Url: "http://rayzurbock.com/ST/icons/BigTalker@2x-118.png")`

Are these hosted elsewhere now?  

Thanks,

Dan W.

**Comment by rayzurbock** [comment]
They are but the redirect was broken.  I've corrected the issue now.
