### ISSUE TITLE
My Apps not in Mobile App

### ISSUE THREAD

**Issue by merrick777** [rayzurbock/SmartThings-BigTalker#4]
Thanks for such perfectly detailed instructions, up to the mobile app... In mobile app -> Marketplace -> SmartApps -> "My Apps" does not exist in ST Mobile V.2.3.0.
Can you let me know what to do?
Thanks so much

**Comment by rayzurbock** [comment]
Which phone/device are you using?
You might have to kill the SmartThings app and relaunch after step 6 so the app reloads and recognizes that it has custom SmartApps.  I thought they fixed this but it may still be needed.

**Comment by merrick777** [comment]
iPhone 6. I closed the app and re-opened but still no 'My apps'

**Comment by merrick777** [comment]
Might the "X" in the icon mean anything?
![screen shot 2017-03-14 at 12 12 43 am](https://cloud.githubusercontent.com/assets/22691436/23885665/1c8b1c14-084b-11e7-9f85-bc6ca1740e54.jpg)

**Comment by rayzurbock** [comment]
No, the X means there is an updated version available to the one you currently have installed.

________________________________

**Comment by merrick777** [comment]
So I still cannot find the self-published apps. I was just reading old blogs that said you need to log out and then log back in for 'My Apps' to be there, but that didn't work either. Still trying, but you have any other suggestions?

**Comment by merrick777** [comment]
I asked ST Support where My Apps can be found in the app - I thought you'd like to see their response:

> Hi,
> Thanks for contacting SmartThings Support! Very sorry for the trouble.
> It seems you have installed your custom SmartApp code on our NA01 server - https://graph.api.smartthings.com
> In order to show your "My Apps" Section in your SmartThings application, you will need to install that same code on our NA02 server - https://graph-na02-useast1.api.smartthings.com
> We apologize for the confusion that our servers have caused, but please let me know if you run into any other problems
> Regards

I started over and used the server they specified, and I'm now all set up! 'MyApps' showed under 'SmartApps' in the mobile app. Time for me to play!! One last thing- your github instructions are the best I've seen (most detail, accurate) - THANKS FOR THAT! Wanted to point out just one minor correction needed.... See screenshot - This should be "PUBLISH", not "PUBLIC".

Thanks!

![screen shot 2017-03-14 at 2 17 50 pm](https://cloud.githubusercontent.com/assets/22691436/23916077/69c158a6-08c1-11e7-85df-c2c563043830.jpg)

**Comment by rayzurbock** [comment]
That is very interesting what support told you.  I hope they get that fixed soon.

I updated the installation instructions.  Thanks for the heads up.
