### ISSUE TITLE
Switch 3 not working without modifying code

### ISSUE THREAD

**Issue by roblandry** [rayzurbock/SmartThings-BigTalker#5]
This is missing:
<code>
def onSwitch3Event(evt){
    processSwitchEvent(3, evt)
}</code>

**Comment by rayzurbock** [comment]
Thanks for catching that.
I've included the fix in 1.0.3-Alpha5 ( still in development ).  I'll be adding a few more things to it before posting it up for testing in the 1.0.3-Dev branch.  The development branch for 1.0.3 is here:  https://github.com/rayzurbock/SmartThings-BigTalker/tree/1.0.3-Dev

**Comment by roblandry** [comment]
Im running alpha 4 right now and works great. Only thing im curious at the moment if there is a way to say all lights are off/on. Right now it only says the first to come on/off if multiple turn on/off at once. Great app!

**Comment by rayzurbock** [comment]
@roblandry, possibly.  Submit it as a new issue and I'll flag it as a feature request to look into.  I think it will take significant code changes and time to implement.

**Comment by rayzurbock** [comment]
Published 1.0.3-Alpha5 in the development branch with this resolved.
