### ISSUE TITLE
Notification If Motion fields for "inactive" or Contact field for "closed" is empty

### ISSUE THREAD

**Issue by tuhinz** [rayzurbock/SmartThings-BigTalker#5]
First off- a massive thanks for all your effort in compiling this app. Terrific job!
I have been using this for quite a while without a hitch but after the latest update (App version: 1.1.11) i am getting error notifications as " ERROR: bigtalker - check configuration. phrase is empty for _**Devicename**_ "
Looking at the logs ( see cleaned up log below) it seems the error appears because the field for "Say this on motion inactive:" under "Motion" is empty . 

Im also getting the same error for "Contact" and it seems it is because the "Say this for contact closed:" field is empty. 

Am i doing anything wrong?  

19:49:51: error BIGTALKER(1.1.11) || ERROR: bigtalker - check configuration. phrase is empty for _**Devicename**_
19:49:51: debug BIGTALKER(1.1.11) || (onMotionEvent): motion, 3, inactive
19:49:51: debug BIGTALKER(1.1.11) || Remain silent while in mode _**Mode**_
19:49:51: debug BIGTALKER(1.1.11) || (onMotionEvent): motion, 1, inactive
19:49:35: trace BIGTALKER(1.1.11) || TALK(motion) |sS| _**AudioDevice**_ | Sending speak().
19:49:35: trace BIGTALKER(1.1.11) || TALK(motion) |sS| >> _**Text for motion detection**_
19:49:35: debug BIGTALKER(1.1.11) || (onMotionEvent): motion, 3, active
19:49:35: debug BIGTALKER(1.1.11) || Remain silent while in mode _**Mode**_
19:49:35: debug BIGTALKER(1.1.11) || (onMotionEvent): motion, 1, active

**Comment by abhaxus** [comment]
Same issue here. I see that in 1.1.10 changelog there is a mention of a corrected null check. Is it possible this is an unintentional consequence?

**Comment by tuhinz** [comment]
Temporarily resolved it by commenting out the code which checks for null text (lines 3642-3644). There must be a better way but im no programmer :)

**Comment by rayzurbock** [comment]
Checking into this.  Standby and I'll have it resolved soon

**Comment by rayzurbock** [comment]
I have published BigTalker 1.1.12 which resolves this issue.  
I'll adjust the 1.1.11 to notify users of an updated version once I receive confirmation that it's working (beyond my own testing which was successful).
