### ISSUE TITLE
Setting Time Constraints

### ISSUE THREAD

**Issue by tuhinz** [rayzurbock/SmartThings-BigTalker#9]
Whether under the "Configure Defaults" setting or within individual Event settings - once a "Dont't talk after" time is set to a certain time, I am not able to change the filed back to empty. If i leave the field empty it gives me a "Please fill out all required fields" error.

Not sure if i should post this as a separate bug but just before i discovered the above, I also found that speak on motion was not working properly. If no default time periods are set either in "Configure Defaults" or in Individual events, BigTalker would not talk. I had set up talk for motion without any time constraints but it would not talk with the following message in the log files: "remain silent in current time period".
I set up a time period to check and then it worked ok. However i cannot now reset the periods to empty and check again because of the first issue mentioned above. 

LOG extract:

 07199623-a50c-4aae-811e-79d773d902fe 09:46:33: debug BIGTALKER(1.1.12) || Remain silent in current time period
07199623-a50c-4aae-811e-79d773d902fe 09:46:33: debug BIGTALKER(1.1.12) || (onMotionEvent): motion, 1, active
07199623-a50c-4aae-811e-79d773d902fe 09:46:33: debug BIGTALKER(1.1.12) || Remain silent in current time period
07199623-a50c-4aae-811e-79d773d902fe 09:46:33: debug BIGTALKER(1.1.12) || (onMotionEvent): motion, 3, active

**Comment by rayzurbock** [comment]
The inability to clear the Don't Speak After field is due to a bug in the Android SmartThings app. I've filed a support request for them to fix this, but it may not get attention without others also submitting the same.

To clear the field on Android, first clear the Don't Talk Before time, press Done then go back into the event and clear the Don't Talk After time.

________________________________

**Comment by tuhinz** [comment]
Thanks Brian, 

The fix works great. I can "unset" the time now. Will log a call with samsung regarding this.
The second issue still remains though. I have a smart routine called "Night" where any motion in the rooms other than the bedroom should output a message but it doesn't. The log says "Remain silent while in mode Night". 
I have not set up any "Do not talk" time defaults for the time when the event is occurring. The output also works fine when i am in a different mode which has a similar setup to the "Night" mode. The only difference is the motion sensor group is the 3rd one - Not sure if there is a bug with the group. I will move the groups around and see if it makes a difference.

**Comment by rayzurbock** [comment]
If you do not mind testing development code, please try the latest in-development version of 2.0 which is here:  https://community.smartthings.com/t/bigtalker-2-0-development/55305/29

Please note, this branch is constantly adding/adjusting/removing features based on feedback and has at least once required a complete removal and re-install to resolve an issue (which I work to prevent, but it was unavoidable in this instance).
The current version is P2.0.a6 and C2.0.a6.
I highly recommend using GitHub Integration to retrieve the updates.
When installing, "Publish the parent and save the child"

**Comment by tuhinz** [comment]
Sure .. just installed the V2.0.
I do not have the option of GitHub integration (probably as i'm outside US) so i've  used the raw code.

Still trying to understand the concept of "Event Groups". 
Currently, I have different spoken text for different triggers (motion, contact etc) depending on the mode the hub is in. In the old version of BT, I used the groups within each event type (Contact, Motion etc) to define the spoken text for each mode. Since i have more than 3 modes, the old version had a limitation and i had to group the actions of multiple modes under the same group. This is now solved by the new 2.0 as you can create unlimited (i think) event groups.

I have a few possible bugs that I will open a new issue for- hope thats ok.

**Comment by rayzurbock** [comment]
One example is to think of "Event Groups" like rooms in SmartThings.  You could create an Event Group for your "Family Room" which encompasses the switches, contacts, thermostats, etc and the desired phrases for that room.  You could have more than one "Family Room" if you had different settings for some switches in the same room than others.

It's really just what you make of it, but it gives you unlimited # of groups vs. just 3 per device type in 1.x versions.

**Comment by rayzurbock** [comment]
I believe the 2.0 development branch resolves this issue and I'm focusing on that branch.
Closing this issue
